name: dotnet package

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code form repo
        uses: actions/checkout@v4

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build
